spring.datasource.url=jdbc:postgresql://dpg-d7eucsh9rddc73eg9j60-a:5432/onlinesender_8ldm
spring.datasource.username=choudhary
spring.datasource.password=FPC5bcJtvxnH2hpXU1ZJQtPLiG7PGk0r
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false